services:
  mysql:
    container_name: hotelbooking_app
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotelbooking_app
    ports:
      - "3308:3308"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
volumes:
  mysql: