services:
  mysql:
    container_name: hotel_booking_db
    image: mysql:latest
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking
    ports:
      - "3308:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - hotel-networks
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  hotel-booking-api:
    container_name: hotel-booking-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hotel_booking_db:3306/hotel_booking
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_TEST-ON-BORROW: true
      SPRING_DATASOURCE_VALIDATION-QUERY: SELECT 1
    depends_on:
      - mysql
    ports:
      - "5051:5051"
    networks:
      - hotel-networks
    restart: always
volumes:
  mysql:
networks:
  hotel-networks:
    driver: bridge
