services:
  mysql:
    container_name: hotel_booking_app
    image: mysql:latest
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking
    ports:
      - "3308:3308"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
volumes:
  mysql: